_wandb:
    value:
        cli_version: 0.21.0
        e:
            37gzeqvsprsbtz3k79jdyqyuqhyfiry5:
                args:
                    - --node-ip-address=10.195.245.11
                    - --node-manager-port=36757
                    - --object-store-name=/tmp/ray/session_2025-08-12_11-08-20_260309_4050250/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-08-12_11-08-20_260309_4050250/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=56447
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=63900
                    - --gcs-address=10.195.245.11:65270
                    - --session-name=session_2025-08-12_11-08-20_260309_4050250
                    - --temp-dir=/tmp/ray
                    - --webui=127.0.0.1:8265
                    - --cluster-id=26f131202d6f178e028996127e2c8c2527fc0deab6e043e51bc7fdeb
                    - --startup-token=32
                    - --worker-launch-time-ms=1754989720720
                    - --node-id=812d75a1d2524a6a03cdbc01289791aebb54472c6e571930bb552a6c
                    - --runtime-env-hash=-1624044036
                    - --enable-resource-isolation=false
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "105089261568"
                        used: "25164468224"
                email: pl03818948@gmail.com
                executable: /dss/dssfs05/pn39qo/pn39qo-dss-0001/tong/miniconda3/envs/verl/bin/python3
                git:
                    commit: eb4ed4ac619a9db95abe7017105170452b35a5db
                    remote: https://github.com/TongLiu-github/verl_multi.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-95031462-a747-c104-8125-a2401bf04a10
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-1ec3508c-d167-a6b3-f947-a9f71e3921ba
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-048cdbd2-3e75-faa0-3620-f68936f6400f
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-592554ac-e62e-7523-edfb-09fcd6bea6a9
                host: mcml-hgx-a100-011
                memory:
                    total: "1081818390528"
                os: Linux-5.15.0-140-generic-x86_64-with-glibc2.35
                program: /dss/dssfs05/pn39qo/pn39qo-dss-0001/tong/miniconda3/envs/verl/lib/python3.10/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.10.0
                root: /dss/dssfs05/pn39qo/pn39qo-dss-0001/tong/grpo/verl_multi
                slurm:
                    cluster_name: lrz
                    conf: /etc/slurm-llnl/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: default
                    job_cpus_per_node: "32"
                    job_end_time: "1755162475"
                    job_gid: "4314506"
                    job_gpus: 0,1,2,3
                    job_id: "5274181"
                    job_name: run_3b_mixed_llamai3b.sh
                    job_nodelist: mcml-hgx-a100-011
                    job_num_nodes: "1"
                    job_partition: mcml-hgx-a100-80x4
                    job_qos: mcml
                    job_start_time: "1754989675"
                    job_uid: "4334380"
                    job_user: di38cuf
                    jobid: "5274181"
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: mcml-hgx-a100-011
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /dss/dssfs05/pn39qo/pn39qo-dss-0001/tong/grpo/verl_multi/run
                    submit_host: login-02
                    task_pid: "4050088"
                    tasks_per_node: "1"
                    topology_addr: mcml-hgx-a100-011
                    topology_addr_pattern: node
                    tres_per_task: cpu=32
                startedAt: "2025-08-12T09:10:32.098244Z"
                writerId: 37gzeqvsprsbtz3k79jdyqyuqhyfiry5
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 95
                - 98
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 95
                - 98
                - 105
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.0
            "5": 0.21.0
            "6": 4.51.1
            "12": 0.21.0
            "13": linux-x86_64
actor_rollout_ref:
    value:
        actor:
            checkpoint:
                load_contents:
                    - model
                    - optimizer
                    - extra
                save_contents:
                    - model
                    - optimizer
                    - extra
            clip_ratio: 0.2
            clip_ratio_c: 3
            clip_ratio_high: 0.2
            clip_ratio_low: 0.2
            entropy_checkpointing: false
            entropy_coeff: 0
            entropy_from_logits_with_chunking: false
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                offload_policy: false
                optimizer_offload: true
                param_offload: true
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            grad_clip: 1
            kl_loss_coef: 0
            kl_loss_type: low_var_kl
            loss_agg_mode: token-mean
            optim:
                lr: 1e-06
                lr_warmup_steps: -1
                lr_warmup_steps_ratio: 0
                min_lr_ratio: 0
                num_cycles: 0.5
                total_training_steps: 29
                warmup_style: constant
                weight_decay: 0.01
            policy_loss:
                clip_cov_lb: 1
                clip_cov_ratio: 0.0002
                clip_cov_ub: 5
                kl_cov_ratio: 0.0002
                loss_mode: vanilla
                ppo_kl_coef: 0.1
            ppo_epochs: 1
            ppo_max_token_len_per_gpu: 24000
            ppo_micro_batch_size: null
            ppo_micro_batch_size_per_gpu: null
            ppo_mini_batch_size: 256
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            shuffle: false
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_dynamic_bsz: true
            use_kl_loss: true
            use_torch_compile: true
        hybrid_engine: true
        model:
            custom_chat_template: null
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            exclude_modules: null
            external_lib: null
            fused_kernel_options:
                impl_backend: torch
            lora_alpha: 16
            lora_rank: 0
            path: meta-llama/Llama-3.2-3B-Instruct
            target_modules: all-linear
            trust_remote_code: false
            use_fused_kernels: false
            use_liger: false
            use_remove_padding: true
            use_shm: false
        ref:
            entropy_checkpointing: false
            entropy_from_logits_with_chunking: false
            fsdp_config:
                forward_prefetch: false
                param_offload: true
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            log_prob_max_token_len_per_gpu: 24000
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: 16
            log_prob_use_dynamic_bsz: true
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_torch_compile: true
        rollout:
            agent:
                custom_async_server:
                    name: null
                    path: null
                num_workers: 8
            calculate_log_probs: false
            disable_log_stats: true
            do_sample: true
            dtype: bfloat16
            enable_chunked_prefill: true
            enforce_eager: true
            engine_kwargs:
                sglang:
                    attention_backend: null
                vllm:
                    disable_mm_preprocessor_cache: false
                    swap_space: null
            free_cache_engine: true
            gpu_memory_utilization: 0.6
            ignore_eos: false
            layered_summon: false
            load_format: dummy_dtensor
            log_prob_max_token_len_per_gpu: 24000
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: 16
            log_prob_use_dynamic_bsz: true
            max_model_len: null
            max_num_batched_tokens: 8192
            max_num_seqs: 1024
            mode: sync
            multi_stage_wake_up: false
            multi_turn:
                completion_callback: null
                enable: false
                format: hermes
                interaction_config_path: null
                max_assistant_turns: null
                max_parallel_calls: 1
                max_tool_response_length: 256
                max_user_turns: null
                tokenization_sanity_check_mode: strict
                tool_config_path: null
                tool_response_truncate_side: middle
                use_inference_chat_template: false
            "n": 2
            name: vllm
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            prompt_length: 512
            response_length: 2048
            temperature: 1
            tensor_model_parallel_size: 2
            top_k: -1
            top_p: 1
            use_multi_prompt: true
            val_kwargs:
                do_sample: false
                "n": 1
                temperature: 0
                top_k: -1
                top_p: 1
algorithm:
    value:
        _target_: verl.trainer.config.AlgoConfig
        adv_estimator: grpo
        gamma: 1
        kl_ctrl:
            _target_: verl.trainer.config.KLControlConfig
            horizon: 10000
            kl_coef: 0
            target_kl: 0.1
            type: fixed
        kl_penalty: kl
        lam: 1
        norm_adv_by_std_in_grpo: true
        pf_ppo:
            _target_: verl.trainer.config.PFPPOConfig
            reweight_method: pow
            weight_pow: 2
        use_kl_in_reward: false
        use_pf_ppo: false
critic:
    value:
        checkpoint:
            load_contents:
                - model
                - optimizer
                - extra
            save_contents:
                - model
                - optimizer
                - extra
        cliprange_value: 0.5
        forward_max_token_len_per_gpu: 32768
        forward_micro_batch_size: null
        forward_micro_batch_size_per_gpu: null
        grad_clip: 1
        loss_agg_mode: token-mean
        model:
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            external_lib: null
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                offload_policy: false
                optimizer_offload: false
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            lora_alpha: 16
            lora_rank: 0
            path: ~/models/deepseek-llm-7b-chat
            target_modules: all-linear
            tokenizer_path: meta-llama/Llama-3.2-3B-Instruct
            trust_remote_code: false
            use_remove_padding: false
            use_shm: false
        optim:
            lr: 1e-05
            lr_warmup_steps_ratio: 0
            min_lr_ratio: null
            total_training_steps: 29
            warmup_style: constant
            weight_decay: 0.01
        ppo_epochs: 1
        ppo_max_token_len_per_gpu: 32768
        ppo_micro_batch_size: null
        ppo_micro_batch_size_per_gpu: null
        ppo_mini_batch_size: 256
        profiler:
            _target_: verl.utils.profiler.ProfilerConfig
            all_ranks: false
            discrete: false
            ranks: []
        rollout_n: 2
        shuffle: false
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: true
custom_reward_function:
    value:
        name: compute_score
        path: null
data:
    value:
        custom_cls:
            name: null
            path: null
        dataloader_num_workers: 8
        filter_overlong_prompts: true
        filter_overlong_prompts_workers: 1
        image_key: images
        max_prompt_length: 512
        max_response_length: 2048
        prompt_key: prompt
        return_full_prompt: false
        return_multi_modal_inputs: true
        return_raw_chat: false
        return_raw_input_ids: false
        reward_fn_key: data_source
        sampler:
            class_name: null
            class_path: null
        shuffle: true
        tokenizer: null
        train_batch_size: 256
        train_files: /dss/dssfs05/pn39qo/pn39qo-dss-0001/tong/safety/verl/data/MATH-mixedprompt-v3/train.parquet
        truncation: error
        trust_remote_code: false
        use_shm: false
        val_batch_size: 1312
        val_files: /dss/dssfs05/pn39qo/pn39qo-dss-0001/tong/safety/verl/data/MATH-500/test.parquet
        validation_shuffle: false
        video_key: videos
ray_init:
    value:
        num_cpus: null
        timeline_json_file: null
reward_model:
    value:
        enable: false
        forward_max_token_len_per_gpu: 32768
        launch_reward_fn_async: false
        max_length: null
        micro_batch_size: null
        micro_batch_size_per_gpu: null
        model:
            external_lib: null
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            input_tokenizer: meta-llama/Llama-3.2-3B-Instruct
            path: ~/models/FsfairX-LLaMA3-RM-v0.1
            trust_remote_code: false
            use_fused_kernels: false
            use_remove_padding: false
            use_shm: false
        profiler:
            _target_: verl.utils.profiler.ProfilerConfig
            all_ranks: false
            discrete: false
            ranks: []
        reward_manager: naive
        sandbox_fusion:
            max_concurrent: 64
            memory_limit_mb: 1024
            url: null
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: true
trainer:
    value:
        balance_batch: true
        controller_nsight_options:
            cuda-graph-trace: graph
            cuda-memory-usage: "true"
            trace: cuda,nvtx,cublas,ucx
        critic_warmup: 0
        default_hdfs_dir: null
        default_local_dir: checkpoints/r1-verl-grpo/r1training_grpo_llamai3b_mixed_v3_2epochs1
        del_local_ckpt_after_load: false
        device: cuda
        esi_redundant_time: 0
        experiment_name: r1training_grpo_llamai3b_mixed_v3_2epochs1
        log_rollout_generations: 0
        log_val_generations: 0
        logger:
            - wandb
        max_actor_ckpt_to_keep: null
        max_critic_ckpt_to_keep: null
        n_gpus_per_node: 4
        nnodes: 1
        npu_profile:
            options:
                analysis: true
                level: level1
                record_shapes: false
                save_path: ./profiler_data
                with_cpu: true
                with_memory: false
                with_module: false
                with_npu: true
                with_stack: false
        profile_steps: null
        project_name: r1-verl-grpo
        ray_wait_register_center_timeout: 300
        resume_from_path: null
        resume_mode: auto
        rollout_data_dir: null
        rollout_save_dir: /dss/dssfs05/pn39qo/pn39qo-dss-0001/tong/grpo/verl_multi/saved_rollout/r1training_grpo_llamai3b_mixed_v3_2epochs1
        save_freq: 290
        save_rollout_generations: true
        test_freq: 2
        total_epochs: 1
        total_training_steps: null
        val_before_train: true
        val_only: false
        validation_data_dir: null
        worker_nsight_options:
            capture-range: cudaProfilerApi
            capture-range-end: null
            cuda-graph-trace: graph
            cuda-memory-usage: "true"
            kill: none
            trace: cuda,nvtx,cublas,ucx
